version: '3.8'

services:
  php:
    image: dockerponome/devops-test-project:latest
    container_name: php-app
    environment:
      - APP_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
